[tool.towncrier]
# Read https://github.com/ethereum/eth-typing/newsfragments/README.md for instructions
package = "eth-typing"
filename = "docs/release_notes.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/ethereum/eth-typing/issues/{issue}>`__" 
